# # -*- coding: utf-8 -*-
# """SowCalcmonthly_withgraphs.ipynb

# Automatically generated by Colab.

# Original file is located at
#     https://colab.research.google.com/drive/1PuWCkIYyL0bqXyvY2m5nC-6b7pxMJbZ5
# """

# !pip install streamlit

import pandas as pd
import ipywidgets as widgets
from IPython.display import display

# -------------------------------
# Sow Rotation Simulator with realistic monthly sales
# -------------------------------
def sow_rotation_simulator(
    total_sows=30,
    piglets_per_cycle=10,
    piglet_mortality=0.07,
    abortion_rate=0.0,
    sow_feed_price=30,
    sow_feed_intake=2.8,
    grower_feed_price=30,
    fcr=3.1,
    final_weight=105,
    sale_price=180,
    management_fee=0,
    management_commission=0.0,
    supervisor_salary=25000,
    worker_salary=18000,
    n_workers=2,
    shed_cost=1_500_000,
    shed_life_years=10,
    sow_cost=35000,
    sow_life_years=4,
    loan_amount=4000000,
    interest_rate=12.1,
    loan_tenure_years=5,
    moratorium_months=0,
    medicine_cost=10000,
    electricity_cost=5000,
    land_lease=10000,
    months=60
):
    current_sows = total_sows
    monthly_data = []

    shed_dep_rate = 1 / (shed_life_years * 12)
    sow_dep_rate = 1 / (sow_life_years * 12)

    total_months = loan_tenure_years * 12
    monthly_rate = interest_rate / 12
    emi = 0
    if loan_amount > 0 and total_months > 0:
        emi = loan_amount * monthly_rate * (1 + monthly_rate)**total_months / ((1 + monthly_rate)**total_months - 1)
    loan_balance = loan_amount

    average_cycle_length = 3.8 + 1.3 + 0.33
    sows_to_mate_per_month = total_sows / average_cycle_length

    batches = []
    ready_for_sale_batches = []
    total_sow_cost = sow_cost * total_sows
    total_capital_invested = shed_cost + total_sow_cost
    cumulative_cash_flow = -total_capital_invested
    total_pigs_born = 0
    total_pigs_sold = 0

    first_sale_cash_needed = 0
    first_sale_done = False

    for month in range(1, months + 1):
        sow_feed_cost = current_sows * sow_feed_intake * 30 * sow_feed_price
        staff_cost = supervisor_salary + n_workers * worker_salary
        mgmt_fixed = management_fee

        sows_crossed = 0
        if month >= 2:
            sows_to_mate = sows_to_mate_per_month
            sows_pregnant = sows_to_mate * (1 - abortion_rate)
            sows_crossed = sows_to_mate  # track how many sows were crossed this month
            if sows_pregnant > 0:
                farrow_month = month + 4
                wean_month = farrow_month + 1
                grower_start_month = wean_month
                grower_end_month = grower_start_month + 6
                piglets = sows_pregnant * piglets_per_cycle * (1 - piglet_mortality)
                total_pigs_born += piglets
                batches.append({
                    'batch_id': len(batches) + 1,
                    'farrow_month': farrow_month,
                    'wean_month': wean_month,
                    'grower_start_month': grower_start_month,
                    'grower_end_month': grower_end_month,
                    'piglets': piglets,
                    'grower_feed_per_month': (piglets * fcr * final_weight) / 6,
                    'sold': False
                })


        # Count piglets in lactation
        piglets_with_sow = sum(batch['piglets'] for batch in batches if batch['farrow_month'] <= month < batch['wean_month'])
        # Count growers
        current_growers = sum(batch['piglets'] for batch in batches if batch['grower_start_month'] <= month < batch['grower_end_month'])
        # Calculate grower feed
        grower_feed_cost = sum(batch['grower_feed_per_month'] * grower_feed_price for batch in batches if batch['grower_start_month'] <= month < batch['grower_end_month'])

        # Identify batches ready for sale
        for batch in batches:
            if batch['grower_end_month'] <= month and not batch['sold'] and batch not in ready_for_sale_batches:
                ready_for_sale_batches.append(batch)

        sold_pigs = 0
        revenue = 0
        # Monthly sale logic (sell all ready batches)
        if ready_for_sale_batches:
            pigs_sold_this_month = 0
            batches_sold_ids = []
            for batch in ready_for_sale_batches:
                pigs_sold_batch = batch['piglets']
                pigs_sold_this_month += pigs_sold_batch
                batch['sold'] = True
                batches_sold_ids.append(batch['batch_id'])
            revenue += pigs_sold_this_month * final_weight * sale_price
            sold_pigs = pigs_sold_this_month
            total_pigs_sold += sold_pigs
            current_growers -= sold_pigs

            # Remove sold batches from ready list
            ready_for_sale_batches = [b for b in ready_for_sale_batches if b['batch_id'] not in batches_sold_ids]

        # Track first sale working capital
        if not first_sale_done:
            first_sale_cash_needed += sow_feed_cost + grower_feed_cost + staff_cost + mgmt_fixed + medicine_cost + electricity_cost + land_lease
        if sold_pigs > 0 and not first_sale_done:
            first_sale_done = True

        mgmt_comm_cost = revenue * management_commission
        other_fixed = medicine_cost + electricity_cost + land_lease
        total_operating_cost = sow_feed_cost + grower_feed_cost + staff_cost + mgmt_fixed + mgmt_comm_cost + other_fixed
        dep = shed_cost * shed_dep_rate + total_sow_cost * sow_dep_rate

        if month <= moratorium_months:
            loan_payment = loan_balance * monthly_rate
        elif month <= total_months:
            interest = loan_balance * monthly_rate
            principal = emi - interest
            loan_balance -= principal
            loan_payment = emi
        else:
            loan_payment = 0

        monthly_profit = revenue - total_operating_cost - dep - loan_payment
        monthly_cash_flow = revenue - total_operating_cost - loan_payment
        cumulative_cash_flow += monthly_cash_flow

        monthly_data.append({
            'Month': month,
            'Sows_Crossed': round(sows_crossed),
            'Piglets_Born_Alive': piglets_with_sow,
            'Growers': current_growers,
            'Sold_Pigs': sold_pigs,
            'Sow_Feed_Cost': round(sow_feed_cost),
            'Grower_Feed_Cost': round(grower_feed_cost),
            'Staff_Cost': round(staff_cost),
            'Other_Fixed_Costs': round(other_fixed),
            'Mgmt_Fee': round(mgmt_fixed),
            'Mgmt_Comm': round(mgmt_comm_cost),
            'Total_Operating_Cost': round(total_operating_cost),
            'Revenue': round(revenue),
            'Loan_EMI': round(loan_payment),
            'Depreciation': round(dep),
            'Monthly_Cash_Flow': round(monthly_cash_flow),
            'Monthly_Profit': round(monthly_profit),
            'Cumulative_Cash_Flow': round(cumulative_cash_flow)
        })

    df_month = pd.DataFrame(monthly_data)

    # Yearly summary
    df_year = df_month.groupby(((df_month['Month']-1)//12)*12).sum()
    df_year.index = [f"Year {i+1}" for i in range(len(df_year))]

    df_year['Cash_Profit'] = df_year['Revenue'] - df_year['Total_Operating_Cost']
    df_year['Profit_After_Dep_Loan'] = df_year['Cash_Profit'] - df_year['Depreciation'] - df_year['Loan_EMI']

    df_year['Total_Crossings'] = df_month.groupby(((df_month['Month']-1)//12)*12)['Sows_Crossed'].sum().values

    # Total animals left in shed
    animals_left = sum(batch['piglets'] for batch in batches if not batch['sold'] and batch['grower_end_month'] > months)
    total_interest_paid = 0

    loan_balance = loan_amount
    total_interest_paid = 0

    for month in range(1, months + 1):
        monthly_interest = loan_balance * monthly_rate

        if month <= moratorium_months:
            # Interest accrues but no EMI paid
            loan_balance += monthly_interest  # capitalize interest
            loan_payment = 0
        elif month <= total_months:
            # EMI payment starts
            principal = emi - monthly_interest
            loan_balance -= principal
            loan_payment = emi
        else:
            loan_payment = 0
            monthly_interest = 0

        total_interest_paid += monthly_interest


    # Define total capital for financial calculations
    total_capital = total_sow_cost + shed_cost

    # Use the per-month cumulative series from df_month (not the scalar)
    cum_series = df_month['Cumulative_Cash_Flow']

    # Find first month where cumulative cash flow >= 0
    breakeven_indices = cum_series[cum_series >= 0].index
    if len(breakeven_indices) > 0:
        first_idx = breakeven_indices[0]
        break_even_month = int(df_month.at[first_idx, 'Month'])
        # profits after break-even (monthly profit values)
        remaining_profits = df_month.loc[df_month['Month'] >= break_even_month, 'Monthly_Profit']
        avg_profit_after_breakeven = round(remaining_profits.mean(), 2) if not remaining_profits.empty else 0
        profit_after_break_even = remaining_profits.sum() if not remaining_profits.empty else 0
    else:
        break_even_month = None
        avg_profit_after_breakeven = 0
        profit_after_break_even = 0

    # Totals
    total_crossings = int(df_month['Sows_Crossed'].sum()) if 'Sows_Crossed' in df_month.columns else 0
    total_pigs_born = int(total_pigs_born)
    total_pigs_sold = int(total_pigs_sold)
    animals_left = int(animals_left)
    total_interest_paid = float(total_interest_paid) if 'total_interest_paid' in locals() or 'total_interest_paid' in globals() else 0.0

    # Total ROI (over simulation)
    total_roi_pct = (cumulative_cash_flow / total_capital) * 100 if total_capital > 0 else 0

    # Average monthly profit (overall)
    average_monthly_profit = df_month['Monthly_Profit'].mean()

    # Return all relevant data for plotting and summary
    return df_month, df_year, total_sow_cost, shed_cost, first_sale_cash_needed, total_pigs_sold, total_pigs_born, animals_left, cumulative_cash_flow, total_interest_paid, break_even_month, profit_after_break_even, average_monthly_profit, avg_profit_after_breakeven, total_crossings, total_roi_pct

# -------------------------------
# ipywidgets UI
# -------------------------------
print("🐷 House of Supreme Ham Simulator")

# Sow & Piglet
total_sows_slider = widgets.IntSlider(min=10, max=200, step=1, value=30, description="Total Sows")
piglets_per_cycle_slider = widgets.IntSlider(min=5, max=30, step=1, value=10, description="Piglets per Cycle")
piglet_mortality_pct_slider = widgets.IntSlider(min=0, max=50, step=1, value=7, description="Piglet Mortality (%)")
abortion_rate_pct_slider = widgets.IntSlider(min=0, max=50, step=1, value=0, description="Abortion Rate (%)")

# Feed & Sale
sow_feed_price_slider = widgets.IntSlider(min=0, max=50, step=1, value=30, description="Sow Feed Price (₹/kg)")
sow_feed_intake_slider = widgets.FloatSlider(min=0.0, max=8.0, step=0.1, value=2.8, description="Sow Feed Intake (kg/day)")
grower_feed_price_slider = widgets.IntSlider(min=0, max=50, step=1, value=30, description="Grower Feed Price (₹/kg)")
fcr_slider = widgets.FloatSlider(min=2.0, max=4.0, step=0.1, value=3.1, description="Feed Conversion Ratio (FCR)")
final_weight_slider = widgets.IntSlider(min=80, max=250, step=5, value=105, description="Final Weight (kg)")
sale_price_slider = widgets.IntSlider(min=100, max=600, step=10, value=180, description="Sale Price (₹/kg)")

# Management
management_fee_slider = widgets.IntSlider(min=0, max=500000, step=5000, value=0, description="Management Fee (Monthly)")
management_commission_pct_slider = widgets.IntSlider(min=0, max=50, step=1, value=0, description="Management Commission (%)")
supervisor_salary_slider = widgets.IntSlider(min=0, max=200000, step=5000, value=25000, description="Supervisor Salary")
worker_salary_slider = widgets.IntSlider(min=0, max=35000, step=1000, value=18000, description="Worker Salary")
n_workers_slider = widgets.IntSlider(min=0, max=50, step=1, value=2, description="Number of Workers")

# Capital Costs
shed_cost_slider = widgets.IntSlider(min=500000, max=20000000, step=100000, value=1500000, description="Shed Cost")
shed_life_years_slider = widgets.IntSlider(min=1, max=30, step=1, value=10, description="Shed Life (Years)")
sow_cost_slider = widgets.IntSlider(min=20000, max=200000, step=1000, value=35000, description="Sow Cost (per sow)")
sow_life_years_slider = widgets.IntSlider(min=1, max=12, step=1, value=4, description="Sow Life (Years)")

# Loan
loan_amount_slider = widgets.IntSlider(min=0, max=20000000, step=100000, value=4000000, description="Loan Amount")
interest_rate_pct_slider = widgets.IntSlider(min=0, max=20, step=1, value=10, description="Interest Rate (%)")
loan_tenure_years_slider = widgets.IntSlider(min=1, max=20, step=1, value=5, description="Loan Tenure (Years)")
moratorium_months_slider = widgets.IntSlider(min=0, max=24, step=1, value=0, description="Moratorium Period (Months)")

# Other Fixed Costs
medicine_cost_slider = widgets.IntSlider(min=0, max=100000, step=1000, value=10000, description="Medicine Cost (Monthly)")
electricity_cost_slider = widgets.IntSlider(min=0, max=100000, step=1000, value=5000, description="Electricity Cost (Monthly)")
land_lease_slider = widgets.IntSlider(min=0, max=100000, step=1000, value=10000, description="Land Lease (Monthly)")

# Simulation Duration
months_slider = widgets.IntSlider(min=12, max=120, step=12, value=60, description="Simulation Duration (Months)")

# Group sliders in a VBox for display
input_widgets = widgets.VBox([
    total_sows_slider, piglets_per_cycle_slider, piglet_mortality_pct_slider, abortion_rate_pct_slider,
    sow_feed_price_slider, sow_feed_intake_slider, grower_feed_price_slider, fcr_slider, final_weight_slider, sale_price_slider,
    management_fee_slider, management_commission_pct_slider, supervisor_salary_slider, worker_salary_slider, n_workers_slider,
    shed_cost_slider, shed_life_years_slider, sow_cost_slider, sow_life_years_slider,
    loan_amount_slider, interest_rate_pct_slider, loan_tenure_years_slider, moratorium_months_slider,
    medicine_cost_slider, electricity_cost_slider, land_lease_slider,
    months_slider
])

display(input_widgets)

# -------------------------------
# Define interactive function
# -------------------------------
def interactive_simulation(
    total_sows, piglets_per_cycle, piglet_mortality_pct, abortion_rate_pct,
    sow_feed_price, sow_feed_intake, grower_feed_price, fcr,
    final_weight, sale_price, management_fee, management_commission_pct,
    supervisor_salary, worker_salary, n_workers, shed_cost, shed_life_years,
    sow_cost, sow_life_years, loan_amount, interest_rate_pct, loan_tenure_years,
    moratorium_months, medicine_cost, electricity_cost, land_lease, months
):
    # Convert percentage inputs to decimals
    piglet_mortality = piglet_mortality_pct / 100
    abortion_rate = abortion_rate_pct / 100
    management_commission = management_commission_pct / 100
    interest_rate = interest_rate_pct / 100

    # Run the simulation
    df_month, df_year, total_sow_cost, shed_cost_val, first_sale_wc, total_pigs_sold, total_pigs_born, animals_left, cumulative_cash_flow, total_interest_paid, break_even_month, profit_after_break_even, average_monthly_profit, avg_profit_after_breakeven, total_crossings, total_roi_pct = sow_rotation_simulator(
        total_sows, piglets_per_cycle, piglet_mortality, abortion_rate,
        sow_feed_price, sow_feed_intake, grower_feed_price, fcr,
        final_weight, sale_price, management_fee, management_commission,
        supervisor_salary, worker_salary, n_workers, shed_cost, shed_life_years,
        sow_cost, sow_life_years, loan_amount, interest_rate, loan_tenure_years,
        moratorium_months, medicine_cost, electricity_cost, land_lease, months
    )

    # Display Monthly & Yearly Summaries
    print("\nMonthly Summary")
    display(df_month.drop(columns=['Month']))

    print("\nYearly Summary")
    display(df_year)

    # Display Financial Summary
    print("\nFinancial Summary")
    total_capital = total_sow_cost + shed_cost_val # Recalculate total_capital here
    print(f"Total Crossings Done: {total_crossings:,}")
    print(f"Total Pigs Born: {total_pigs_born:,}")
    print(f"Total Pigs Sold: {total_pigs_sold:,}")
    print(f"Animals Remaining in Shed: {animals_left:,}")
    print(f"Total Capital Invested (Shed + Sows): ₹{total_capital:,.2f}")
    print(f"Working Capital till First Sale: ₹{first_sale_wc:,.2f}")

    if break_even_month:
        print(f"Break-even Month: {break_even_month}")
    else:
        print("Break-even: Not achieved within simulation period")

    print(f"Profit After Break-even (cumulative): ₹{profit_after_break_even:,.0f}")
    print(f"Average Monthly Profit: ₹{average_monthly_profit:,.0f}")
    print(f"Average Monthly Profit after Break-even: ₹{avg_profit_after_breakeven:,.2f}")
    print(f"Total Interest Paid Over Loan Tenure: ₹{total_interest_paid:,.0f}")
    print(f"Total ROI: {total_roi_pct:.2f}%")

    # Return df_month for plotting in the next cell
    return df_month


# Link sliders to the interactive function
interactive_output = widgets.interactive(
    interactive_simulation,
    total_sows=total_sows_slider,
    piglets_per_cycle=piglets_per_cycle_slider,
    piglet_mortality_pct=piglet_mortality_pct_slider,
    abortion_rate_pct=abortion_rate_pct_slider,
    sow_feed_price=sow_feed_price_slider,
    sow_feed_intake=sow_feed_intake_slider,
    grower_feed_price=grower_feed_price_slider,
    fcr=fcr_slider,
    final_weight=final_weight_slider,
    sale_price=sale_price_slider,
    management_fee=management_fee_slider,
    management_commission_pct=management_commission_pct_slider,
    supervisor_salary=supervisor_salary_slider,
    worker_salary=worker_salary_slider,
    n_workers=n_workers_slider,
    shed_cost=shed_cost_slider,
    shed_life_years=shed_life_years_slider,
    sow_cost=sow_cost_slider,
    sow_life_years=sow_life_years_slider,
    loan_amount=loan_amount_slider,
    interest_rate_pct=interest_rate_pct_slider,
    loan_tenure_years=loan_tenure_years_slider,
    moratorium_months=moratorium_months_slider,
    medicine_cost=medicine_cost_slider,
    electricity_cost=electricity_cost_slider,
    land_lease=land_lease_slider,
    months=months_slider
)

# Display the interactive output
display(interactive_output)

import matplotlib.pyplot as plt

# Access the df_month from the interactive output
# The interactive_output.result will contain the return value of the function
df_month = interactive_output.result

if df_month is not None:
    # Helper: format month -> Year-Month label
    def format_months(month_num):
        year = (month_num - 1) // 12 + 1
        month = (month_num - 1) % 12 + 1
        return f"{year}-{month}"

    # Create Month_Label column if it doesn't exist
    if 'Month_Label' not in df_month.columns:
        df_month["Month_Label"] = df_month["Month"].apply(format_months)

    # ---- Revenue vs Total Costs (Stacked) ----
    cost_components = ["Sow_Feed_Cost", "Grower_Feed_Cost", "Staff_Cost", "Other_Fixed_Costs", "Mgmt_Fee", "Mgmt_Comm", "Loan_EMI"]

    fig, ax = plt.subplots(figsize=(10,6))

    # Stacked costs
    ax.stackplot(
        df_month["Month"],
        [df_month[c] for c in cost_components],
        labels=cost_components,
        alpha=0.7
    )

    # Revenue line
    ax.plot(df_month["Month"], df_month["Revenue"], label="Revenue", color="black", linewidth=2)

    ax.set_xlabel("Month")
    ax.set_ylabel("Amount (₹)")
    ax.set_title("Revenue vs Total Costs (Stacked Breakdown)")
    ax.legend(loc="upper left")
    plt.show()

    # # ---- Cumulative Cash Flow ----
    # plt.figure(figsize=(12, 6))
    # plt.plot(df_month['Month'], df_month['Cumulative_Cash_Flow'])
    # plt.xlabel('Month')
    # plt.ylabel('Cumulative Cash Flow')
    # plt.title('Cumulative Cash Flow Over Time')
    # plt.grid(True)
    # plt.show()

    # ---- Monthly Profit ----
    plt.figure(figsize=(12, 6))
    plt.plot(df_month['Month'], df_month['Monthly_Profit'])
    plt.xlabel('Month')
    plt.ylabel('Monthly Profit')
    plt.title('Monthly Profit Over Time')
    plt.grid(True)
    plt.show()
else:
    print("Run the previous cell to generate data for plotting.")



# ---- Plot 2: Cumulative Cash Flow + Cumulative Profit + Cumulative Loan Payments ----
fig, ax = plt.subplots(figsize=(12,7))
ax.plot(df_month["Month_Label"], df_month["Cumulative_Cash_Flow"]/1e5,
        label="Cumulative Cash Flow (₹ Lakhs)", color="green")
ax.plot(df_month["Month_Label"], cumulative_profit/1e5,
        label="Cumulative Profit (₹ Lakhs)", color="blue")
# ax.plot(df_month["Month_Label"], cumulative_loan_payments/1e5,
#         label="Cumulative Loan Payments (₹ Lakhs)", color="purple", linestyle='--')


# 1. Break-even (Cash Flow turns positive)
if break_even_month:
    ax.axvline(break_even_month-1, color="red", linestyle="--",
               label=f"Break Even (Month {break_even_month})")

# 2. First Positive Cumulative Profit
profit_break_even = next((i for i, val in enumerate(cumulative_profit) if val >= 0), None)
if profit_break_even is not None:
    ax.axvline(profit_break_even, color="orange", linestyle="--",
               label=f"Profit Positive (Month {df_month['Month'].iloc[profit_break_even]})")

# 3. Highest Cumulative Cash Flow
max_cf_idx = df_month["Cumulative_Cash_Flow"].idxmax()
ax.scatter(df_month["Month_Label"].iloc[max_cf_idx],
           df_month["Cumulative_Cash_Flow"].iloc[max_cf_idx]/1e5,
           color="darkgreen", s=80, zorder=5, label="Max Cash Flow")

# 4. Highest Cumulative Profit
max_profit_idx = cumulative_profit.idxmax()
ax.scatter(df_month["Month_Label"].iloc[max_profit_idx],
           cumulative_profit.iloc[max_profit_idx]/1e5,
           color="darkblue", s=80, zorder=5, label="Max Profit")

# Styling
ax.set_xlabel("Time (Years-Months)")
ax.set_ylabel("Amount (₹ Lakhs)")
ax.set_title("Cumulative Cash Flow & Profit Over Time (Milestones Marked)")
ax.legend()
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

# Access the df_month from the interactive output
df_month = interactive_output.result

if df_month is not None:
    # ---- Plot 5: Total Costs by Component (Bar Graph) ----
    cost_components = ["Sow_Feed_Cost", "Grower_Feed_Cost", "Staff_Cost", "Other_Fixed_Costs", "Mgmt_Fee", "Mgmt_Comm", "Loan_EMI"]
    total_costs = df_month[cost_components].sum()

    plt.figure(figsize=(10, 6))
    plt.bar(total_costs.index, total_costs.values)
    plt.xlabel("Cost Component")
    plt.ylabel("Total Amount (₹)")
    plt.title("Total Costs by Component Over Simulation Period")
    plt.xticks(rotation=45, ha='right')
    plt.tight_layout()
    plt.show()
else:
    print("Run the simulation cell to generate data for plotting.")



import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

# -------------------------------
# Sow Rotation Simulator with realistic monthly sales
# -------------------------------
def sow_rotation_simulator(
    total_sows=30,
    piglets_per_cycle=10,
    piglet_mortality=0.07,
    abortion_rate=0.0,
    sow_feed_price=30,
    sow_feed_intake=2.8,
    grower_feed_price=30,
    fcr=3.1,
    final_weight=105,
    sale_price=180,
    management_fee=0,
    management_commission=0.0,
    supervisor_salary=25000,
    worker_salary=18000,
    n_workers=2,
    shed_cost=1_500_000,
    shed_life_years=10,
    sow_cost=35000,
    sow_life_years=4,
    loan_amount=4000000,
    interest_rate=12.1,
    loan_tenure_years=5,
    moratorium_months=0,
    medicine_cost=10000,
    electricity_cost=5000,
    land_lease=10000,
    months=60
):
    current_sows = total_sows
    monthly_data = []

    shed_dep_rate = 1 / (shed_life_years * 12)
    sow_dep_rate = 1 / (sow_life_years * 12)

    total_months = loan_tenure_years * 12
    monthly_rate = interest_rate / 12
    emi = 0
    if loan_amount > 0 and total_months > 0:
        emi = loan_amount * monthly_rate * (1 + monthly_rate)**total_months / ((1 + monthly_rate)**total_months - 1)
    loan_balance = loan_amount

    average_cycle_length = 3.8 + 1.3 + 0.33
    sows_to_mate_per_month = total_sows / average_cycle_length

    batches = []
    ready_for_sale_batches = []
    total_sow_cost = sow_cost * total_sows
    total_capital_invested = shed_cost + total_sow_cost
    cumulative_cash_flow = -total_capital_invested
    total_pigs_born = 0
    total_pigs_sold = 0

    first_sale_cash_needed = 0
    first_sale_done = False

    for month in range(1, months + 1):
        sow_feed_cost = current_sows * sow_feed_intake * 30 * sow_feed_price
        staff_cost = supervisor_salary + n_workers * worker_salary
        mgmt_fixed = management_fee

        sows_crossed = 0
        if month >= 2:
            sows_to_mate = sows_to_mate_per_month
            sows_pregnant = sows_to_mate * (1 - abortion_rate)
            sows_crossed = sows_to_mate  # track how many sows were crossed this month
            if sows_pregnant > 0:
                farrow_month = month + 4
                wean_month = farrow_month + 1
                grower_start_month = wean_month
                grower_end_month = grower_start_month + 6
                piglets = sows_pregnant * piglets_per_cycle * (1 - piglet_mortality)
                total_pigs_born += piglets
                batches.append({
                    'batch_id': len(batches) + 1,
                    'farrow_month': farrow_month,
                    'wean_month': wean_month,
                    'grower_start_month': grower_start_month,
                    'grower_end_month': grower_end_month,
                    'piglets': piglets,
                    'grower_feed_per_month': (piglets * fcr * final_weight) / 6,
                    'sold': False
                })


        # Count piglets in lactation
        piglets_with_sow = sum(batch['piglets'] for batch in batches if batch['farrow_month'] <= month < batch['wean_month'])
        # Count growers
        current_growers = sum(batch['piglets'] for batch in batches if batch['grower_start_month'] <= month < batch['grower_end_month'])
        # Calculate grower feed
        grower_feed_cost = sum(batch['grower_feed_per_month'] * grower_feed_price for batch in batches if batch['grower_start_month'] <= month < batch['grower_end_month'])

        # Identify batches ready for sale
        for batch in batches:
            if batch['grower_end_month'] <= month and not batch['sold'] and batch not in ready_for_sale_batches:
                ready_for_sale_batches.append(batch)

        sold_pigs = 0
        revenue = 0
        # Monthly sale logic (sell all ready batches)
        if ready_for_sale_batches:
            pigs_sold_this_month = 0
            batches_sold_ids = []
            for batch in ready_for_sale_batches:
                pigs_sold_batch = batch['piglets']
                pigs_sold_this_month += pigs_sold_batch
                batch['sold'] = True
                batches_sold_ids.append(batch['batch_id'])
            revenue += pigs_sold_this_month * final_weight * sale_price
            sold_pigs = pigs_sold_this_month
            total_pigs_sold += sold_pigs
            current_growers -= sold_pigs

            # Remove sold batches from ready list
            ready_for_sale_batches = [b for b in ready_for_sale_batches if b['batch_id'] not in batches_sold_ids]

        # Track first sale working capital
        if not first_sale_done:
            first_sale_cash_needed += sow_feed_cost + grower_feed_cost + staff_cost + mgmt_fixed + medicine_cost + electricity_cost + land_lease
        if sold_pigs > 0 and not first_sale_done:
            first_sale_done = True

        mgmt_comm_cost = revenue * management_commission
        other_fixed = medicine_cost + electricity_cost + land_lease
        total_operating_cost = sow_feed_cost + grower_feed_cost + staff_cost + mgmt_fixed + mgmt_comm_cost + other_fixed
        dep = shed_cost * shed_dep_rate + total_sow_cost * sow_dep_rate

        if month <= moratorium_months:
            loan_payment = loan_balance * monthly_rate
        elif month <= total_months:
            interest = loan_balance * monthly_rate
            principal = emi - interest
            loan_balance -= principal
            loan_payment = emi
        else:
            loan_payment = 0

        monthly_profit = revenue - total_operating_cost - dep - loan_payment
        monthly_cash_flow = revenue - total_operating_cost - loan_payment
        cumulative_cash_flow += monthly_cash_flow

        monthly_data.append({
            'Month': month,
            'Sows_Crossed': round(sows_crossed),
            'Piglets_Born_Alive': piglets_with_sow,
            'Growers': current_growers,
            'Sold_Pigs': sold_pigs,
            'Sow_Feed_Cost': round(sow_feed_cost),
            'Grower_Feed_Cost': round(grower_feed_cost),
            'Staff_Cost': round(staff_cost),
            'Other_Fixed_Costs': round(other_fixed),
            'Mgmt_Fee': round(mgmt_fixed),
            'Mgmt_Comm': round(mgmt_comm_cost),
            'Total_Operating_Cost': round(total_operating_cost),
            'Revenue': round(revenue),
            'Loan_EMI': round(loan_payment),
            'Depreciation': round(dep),
            'Monthly_Cash_Flow': round(monthly_cash_flow),
            'Monthly_Profit': round(monthly_profit),
            'Cumulative_Cash_Flow': round(cumulative_cash_flow)
        })

    df_month = pd.DataFrame(monthly_data)

    # Yearly summary
    df_year = df_month.groupby(((df_month['Month']-1)//12)*12).sum()
    df_year.index = [f"Year {i+1}" for i in range(len(df_year))]

    df_year['Cash_Profit'] = df_year['Revenue'] - df_year['Total_Operating_Cost']
    df_year['Profit_After_Dep_Loan'] = df_year['Cash_Profit'] - df_year['Depreciation'] - df_year['Loan_EMI']

    df_year['Total_Crossings'] = df_month.groupby(((df_month['Month']-1)//12)*12)['Sows_Crossed'].sum().values

    # Total animals left in shed
    animals_left = sum(batch['piglets'] for batch in batches if not batch['sold'] and batch['grower_end_month'] > months)
    total_interest_paid = 0

    loan_balance = loan_amount
    total_interest_paid = 0

    for month in range(1, months + 1):
        monthly_interest = loan_balance * monthly_rate

        if month <= moratorium_months:
            # Interest accrues but no EMI paid
            loan_balance += monthly_interest  # capitalize interest
            loan_payment = 0
        elif month <= total_months:
            # EMI payment starts
            principal = emi - monthly_interest
            loan_balance -= principal
            loan_payment = emi
        else:
            loan_payment = 0
            monthly_interest = 0

        total_interest_paid += monthly_interest


    # Define total capital for financial calculations
    total_capital = total_sow_cost + shed_cost

    # Use the per-month cumulative series from df_month (not the scalar)
    cum_series = df_month['Cumulative_Cash_Flow']

    # Find first month where cumulative cash flow >= 0
    breakeven_indices = cum_series[cum_series >= 0].index
    if len(breakeven_indices) > 0:
        first_idx = breakeven_indices[0]
        break_even_month = int(df_month.at[first_idx, 'Month'])
        # profits after break-even (monthly profit values)
        remaining_profits = df_month.loc[df_month['Month'] >= break_even_month, 'Monthly_Profit']
        avg_profit_after_breakeven = round(remaining_profits.mean(), 2) if not remaining_profits.empty else 0
        profit_after_break_even = remaining_profits.sum() if not remaining_profits.empty else 0
    else:
        break_even_month = None
        avg_profit_after_breakeven = 0
        profit_after_break_even = 0

    # Totals
    total_crossings = int(df_month['Sows_Crossed'].sum()) if 'Sows_Crossed' in df_month.columns else 0
    total_pigs_born = int(total_pigs_born)
    total_pigs_sold = int(total_pigs_sold)
    animals_left = int(animals_left)
    total_interest_paid = float(total_interest_paid) if 'total_interest_paid' in locals() or 'total_interest_paid' in globals() else 0.0

    # Total ROI (over simulation)
    total_roi_pct = (cumulative_cash_flow / total_capital) * 100 if total_capital > 0 else 0

    # Average monthly profit (overall)
    average_monthly_profit = df_month['Monthly_Profit'].mean()

    # Return all relevant data for plotting and summary
    return df_month, df_year, total_sow_cost, shed_cost, first_sale_cash_needed, total_pigs_sold, total_pigs_born, animals_left, cumulative_cash_flow, total_interest_paid, break_even_month, profit_after_break_even, average_monthly_profit, avg_profit_after_breakeven, total_crossings, total_roi_pct

# -------------------------------
# Streamlit UI
# -------------------------------
st.title("🐷 House of Supreme Ham Simulator")

st.sidebar.header("Adjust Simulation Parameters")

# Sow & Piglet
st.sidebar.subheader("Sow & Piglet Parameters")
total_sows = st.sidebar.slider("Total Sows", 10, 200, 30, 1)
piglets_per_cycle = st.sidebar.slider("Piglets per Cycle", 5, 30, 10, 1)
piglet_mortality_pct = st.sidebar.slider("Piglet Mortality (%)", 0, 50, 7, 1)
abortion_rate_pct = st.sidebar.slider("Abortion Rate (%)", 0, 50, 0, 1)


# Feed & Sale
st.sidebar.subheader("Feed & Sale Parameters")
sow_feed_price = st.sidebar.slider("Sow Feed Price (₹/kg)", 0, 50, 30, 1)
sow_feed_intake = st.sidebar.slider("Sow Feed Intake (kg/day)", 0.0, 8.0, 2.8, 0.1)
grower_feed_price = st.sidebar.slider("Grower Feed Price (₹/kg)", 0, 50, 30, 1)
fcr = st.sidebar.slider("Feed Conversion Ratio (FCR)", 2.0, 4.0, 3.1, 0.1)
final_weight = st.sidebar.slider("Final Weight (kg)", 80, 250, 105, 5)
sale_price = st.sidebar.slider("Sale Price (₹/kg)", 100, 600, 180, 10)

# Management
st.sidebar.subheader("Management Parameters")
management_fee = st.sidebar.slider("Management Fee (Monthly)", 0, 500000, 0, 5000)
management_commission_pct = st.sidebar.slider("Management Commission (%)", 0, 50, 0, 1)
supervisor_salary = st.sidebar.slider("Supervisor Salary", 0, 200000, 25000, 5000)
worker_salary = st.sidebar.slider("Worker Salary", 0, 35000, 18000, 1000)
n_workers = st.sidebar.slider("Number of Workers", 0, 50, 2, 1)

# Capital Costs
st.sidebar.subheader("Capital Costs")
shed_cost = st.sidebar.slider("Shed Cost", 500000, 20000000, 1500000, 100000)
shed_life_years = st.sidebar.slider("Shed Life (Years)", 1, 30, 10, 1)
sow_cost = st.sidebar.slider("Sow Cost (per sow)", 20000, 200000, 35000, 1000)
sow_life_years = st.sidebar.slider("Sow Life (Years)", 1, 12, 4, 1)

# Loan
st.sidebar.subheader("Loan Parameters")
loan_amount = st.sidebar.slider("Loan Amount", 0, 20000000, 4000000, 100000)
interest_rate_pct = st.sidebar.slider("Interest Rate (%)", 0, 20, 10, 1)
loan_tenure_years = st.sidebar.slider("Loan Tenure (Years)", 1, 20, 5, 1)
moratorium_months = st.sidebar.slider("Moratorium Period (Months)", 0, 24, 0, 1)

# Other Fixed Costs
st.sidebar.subheader("Other Fixed Costs")
medicine_cost = st.sidebar.slider("Medicine Cost (Monthly)", 0, 100000, 10000, 1000)
electricity_cost = st.sidebar.slider("Electricity Cost (Monthly)", 0, 100000, 5000, 1000)
land_lease = st.sidebar.slider("Land Lease (Monthly)", 0, 100000, 10000, 1000)

# Simulation Duration
st.sidebar.subheader("Simulation Duration")
months = st.sidebar.slider("Simulation Duration (Months)", 12, 120, 60, 12)


# -------------------------------
# Run Simulation and get results
# -------------------------------
df_month, df_year, total_sow_cost, shed_cost_val, first_sale_wc, total_pigs_sold, total_pigs_born, animals_left, cumulative_cash_flow, total_interest_paid, break_even_month, profit_after_break_even, average_monthly_profit, avg_profit_after_breakeven, total_crossings, total_roi_pct = sow_rotation_simulator(
    total_sows, piglets_per_cycle, piglet_mortality_pct / 100, abortion_rate_pct / 100,
    sow_feed_price, sow_feed_intake, grower_feed_price, fcr,
    final_weight, sale_price, management_fee, management_commission_pct / 100,
    supervisor_salary, worker_salary, n_workers, shed_cost, shed_life_years,
    sow_cost, sow_life_years, loan_amount, interest_rate_pct / 100, loan_tenure_years,
    moratorium_months, medicine_cost, electricity_cost, land_lease, months
)

# -------------------------------
# Display Summaries in Streamlit
# -------------------------------
st.subheader("Simulation Results")

st.write("Monthly Summary")
st.dataframe(df_month.drop(columns=['Month']))

st.write("Yearly Summary")
st.dataframe(df_year)

st.subheader("Financial Summary")
total_capital = total_sow_cost + shed_cost_val
st.write(f"Total Crossings Done: {total_crossings:,}")
st.write(f"Total Pigs Born: {total_pigs_born:,}")
st.write(f"Total Pigs Sold: {total_pigs_sold:,}")
st.write(f"Animals Remaining in Shed: {animals_left:,}")
st.write(f"Total Capital Invested (Shed + Sows): ₹{total_capital:,.2f}")
st.write(f"Working Capital till First Sale: ₹{first_sale_wc:,.2f}")

if break_even_month:
    st.write(f"Break-even Month: {break_even_month}")
else:
    st.write("Break-even: Not achieved within simulation period")

st.write(f"Profit After Break-even (cumulative): ₹{profit_after_break_even:,.0f}")
st.write(f"Average Monthly Profit: ₹{average_monthly_profit:,.0f}")
st.write(f"Average Monthly Profit after Break-even: ₹{avg_profit_after_breakeven:,.2f}")
st.write(f"Total Interest Paid Over Loan Tenure: ₹{total_interest_paid:,.0f}")
st.write(f"Total ROI: {total_roi_pct:.2f}%")


# -------------------------------
# Generate and Display Plots in Streamlit
# -------------------------------
st.subheader("Simulation Plots")

# ---- Plot 1: Revenue vs Total Costs (Stacked) ----
st.write("Revenue vs Total Costs (Stacked Breakdown)")
cost_components = ["Sow_Feed_Cost", "Grower_Feed_Cost", "Staff_Cost", "Other_Fixed_Costs", "Mgmt_Fee", "Mgmt_Comm", "Loan_EMI"]
fig1, ax1 = plt.subplots(figsize=(10,6))
ax1.stackplot(
    df_month["Month"],
    [df_month[c] for c in cost_components],
    labels=cost_components,
    alpha=0.7
)
ax1.plot(df_month["Month"], df_month["Revenue"], label="Revenue", color="black", linewidth=2)
ax1.set_xlabel("Month")
ax1.set_ylabel("Amount (₹)")
ax1.set_title("Revenue vs Total Costs (Stacked Breakdown)")
ax1.legend(loc="upper left")
st.pyplot(fig1)


# ---- Plot 2: Cumulative Cash Flow ----
st.write("Cumulative Cash Flow Over Time")
fig2, ax2 = plt.subplots(figsize=(12, 6))
ax2.plot(df_month['Month'], df_month['Cumulative_Cash_Flow'])
ax2.set_xlabel('Month')
ax2.set_ylabel('Cumulative Cash Flow')
ax2.set_title('Cumulative Cash Flow Over Time')
ax2.grid(True)
st.pyplot(fig2)

# ---- Plot 3: Monthly Profit ----
st.write("Monthly Profit Over Time")
fig3, ax3 = plt.subplots(figsize=(12, 6))
ax3.plot(df_month['Month'], df_month['Monthly_Profit'])
ax3.set_xlabel('Month')
ax3.set_ylabel('Monthly Profit')
ax3.set_title('Monthly Profit Over Time')
ax3.grid(True)
st.pyplot(fig3)

# ---- Plot 4: Monthly Profit and Loan EMI ----
st.write("Monthly Profit and Loan EMI Over Time")
fig4, ax4 = plt.subplots(figsize=(12, 6))
ax4.plot(df_month['Month'], df_month['Monthly_Profit'], label='Monthly Profit')
ax4.plot(df_month['Month'], df_month['Loan_EMI'], label='Monthly Loan EMI')
ax4.set_xlabel('Month')
ax4.set_ylabel('Amount (₹)')
ax4.set_title('Monthly Profit and Loan EMI Over Time')
ax4.grid(True)
ax4.legend()
st.pyplot(fig4)

# ---- Plot 5: Total Costs by Component (Bar Graph) ----
st.write("Total Costs by Component Over Simulation Period")
cost_components = ["Sow_Feed_Cost", "Grower_Feed_Cost", "Staff_Cost", "Other_Fixed_Costs", "Mgmt_Fee", "Mgmt_Comm", "Loan_EMI"]
total_costs = df_month[cost_components].sum()
fig5, ax5 = plt.subplots(figsize=(10, 6))
ax5.bar(total_costs.index, total_costs.values)
ax5.set_xlabel("Cost Component")
ax5.set_ylabel("Total Amount (₹)")
ax5.set_title("Total Costs by Component Over Simulation Period")
ax5.tick_params(axis='x', rotation=45)
plt.tight_layout()
st.pyplot(fig5)

"""**To run this Streamlit application:**

1.  Save the code above as a Python file with a `.py` extension (e.g., `pig_simulator_app.py`).
2.  Open your terminal or command prompt.
3.  Navigate to the directory where you saved the file.
4.  Run the command: `streamlit run pig_simulator_app.py`
5.  Your web browser will open with the Streamlit application.
"""
